name: memories_photos
description: ""
publish_to: 'none'
version: 2026.08.01+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  image: ^4.9.1
  camera: ^0.12.0+1
  image_picker: ^1.2.3

  dynamic_color: ^1.8.1
  keep_screen_on: ^6.0.0
  material_color_utilities: ^0.13.0
  
  flutter_styled_toast: ^2.3.0
  flutter_colorpicker: ^1.1.0
  photo_view: ^0.15.0
  silky_scroll: ^2.6.4

  open_filex: ^4.7.0
  filesystem_picker: ^4.1.0
  url_launcher: ^6.3.2
  
  share_plus: ^13.2.0

  msix: ^3.18.0

# dart run msix:create
msix_config:
  display_name: Memories Photos
  publisher_display_name: mb28
  identity_name: mb28.MonoP
  msix_version: 1.3.0.6
  languages: en-us
  file_extension: .png, .jpeg, .jpg
  logo_path: E:\_Flutter Apps\memories_photos\Things\App Icon Base\AppRect.png
  capabilities: microphone, webcam
  output_path: E:\_Flutter Apps\memories_photos\msix
  output_name: MemoreisPhotos
  # certificate_path: E:\_Flutter Apps\memories_photos\msix\MemoriesPhotos.pfx
  # certificate_password: fake_password
  # architecture: arm64

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/BG.png
    - Things/App Icon Base/AppRect.png

  shaders:
    - Assets/Shaders/bg.frag

  fonts:
    - family: LexendDeca
      fonts:
        - asset: Assets/LexendDeca-Thin.ttf
          weight: 700
        - asset: Assets/LexendDeca-Regular.ttf
        - asset: Assets/LexendDeca-Thin.ttf
          weight: 200
    - family: ElmsSans
      fonts:
        - asset: Assets/ElmsSans-VariableFont_wght.ttf
    - family: CherryBombOne
      fonts:
        - asset: Assets/CherryBombOne-Regular.ttf
